ansible_port: 2222
ansible_conf_port: 2222 # set to same as ansible_port
ansible_python_interpreter: /usr/bin/python3 
packages:
  - gcc
  - clang
  - docker
  - docker-compose
  - htop
  - python3-pip
  - git
  - g++
  - pkg-config
  - git-buildpackage
  - pandoc
  - debhelper
  - libfuse-dev
  - libattr1-dev
  - samba
  - samba-common
  - cifs-utils
cidr: 192.168.100.0/24
server_ip: 192.168.100.99
samba: { 
  label: samba, 
  path: /mnt/storage/samba, 
  users: "{{ username }}", 
  browsable: yes, 
  readonly: no, 
  writable: yes }


