---
- name: Make netplan dir.
  become: true
  file:
    path: /etc/netplan
    state: directory
    owner: root
    group: root

- name: Copy netplan config.
  become: true
  template:
    src: ../templates/netplan.yaml
    dest: /etc/netplan/00-ansible_network.yaml
    owner: root
    group: root

- name: Delete cloud-init installer netplan config.
  become: true
  file:
    path: /etc/netplan/00-installer-config.yaml
    state: absent
  notify: apply netplan



- meta: flush_handlers
