---
- name: Set username as fact.
  become: true
  set_fact:
    username: "{{ ansible_facts.env.USER }}"


- name: Disable login message.
  file:
    path: "/home/{{ username }}/.hushlogin"
    state: touch
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve

- name: Make essential groups.
  become: true
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - "{{ username }}"

- name: Add regular user to groups.
  become: true
  user:
    name: "{{ username }}"
    groups: 
      - docker
      - "{{ username }}"
    append: true
