- name: compose up
  docker_compose:
    project_src: "{{ docker_path }}"
    build: false

- name: compose down
  docker_compose: 
    project_src: "{{ docker_path }}"
    build: false
    stopped: true


- name: compose restart
  docker_compose: 
    project_src: "{{ docker_path }}"
    build: false
    restarted: true

- name: disable systemd-resolved
  become: true
  service:
    name: systemd-resolved
    state: stopped
    enabled: false

# - name: make resolv.conf
#   become: true
#   file:
#     path: /etc/resolv.conf
#     state: touch
#     owner: root
#     group: root
#     mode: "0644"
#
# - name: change nameserver
#   become: true
#   lineinfile:
#     path: /etc/resolv.conf
#     regexp: "^nameserver"
#     line: "nameserver 127.0.0.1"
#     owner: root
#     group: root
#     mode: "0644"
