mergerfs_install_url: "https://github.com/trapexit/mergerfs/releases/download/2.34.1/mergerfs_2.34.1.ubuntu-jammy_amd64.deb"
disk_count: 3
data_path: "/mnt/disk"
parity_path: "/mnt/parity"
secondary_parity_path: "/mnt/disk0"
snapraid_scrub_percent: 22
snapraid_scrub_age: 8

snapraid_sync_schedule:
  minute: 0
  hour: 0
snapraid_sync_healthcheck_io_uuid: ""

snapraid_scrub_schedule:
  minute: 0
  hour: 0
  weekday: 0
snapraid_scrub_healthcheck_io_uuid: ""
